name: mason
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.1
  get_it: ^7.7.0
  go_router: ^14.1.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
