default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      skip_build_archive: true,
      archive_path: "../build/ios/archive/Runner.xcarchive",
    )
    upload_to_testflight
  end

  desc "Promote TestFlight to App Store"
  lane :promote do
    deliver(
      build_number: '1',
      submit_for_review: true,
      automatic_release: true,  
      force: true,
      skip_metadata: true,
      skip_screenshots: true,  
      metadata_path: "./metadata"
    )
  end
end
